Add more properties to Module
me4502/ModularFramework pull request #2
Opened 2017-01-06 07:11 UTC by connorhartley

2017-01-06 07:25 UTC, me4502 requested changes

2017-01-06 07:25 UTC, me4502 commented on src/main/java/com/me4502/modularframework/module/Module.java
> +    String moduleVersion();
These should all have defaults.

I'd recommend 1.0.0 for version, empty array for authors, and redirect ID to moduleName().toLowerCase

2017-01-06 07:25 UTC, me4502 commented on src/main/java/com/me4502/modularframework/module/ModuleWrapper.java
> +        if(Sponge.getPluginManager().fromInstance(owner.getPlugin()).isPresent()) {
This section shouldn't be needed with defaults.

2017-01-06 07:25 UTC, me4502 commented on src/main/java/com/me4502/modularframework/module/ModuleWrapper.java
> +        if(Sponge.getPluginManager().fromInstance(owner.getPlugin()).isPresent()) {
This will only occur if the annotation doesn't exist

2017-01-06 07:37 UTC, connorhartley commented on src/main/java/com/me4502/modularframework/module/Module.java
> +    String moduleVersion();
That better?

2017-01-06 08:56 UTC, me4502 requested changes

2017-01-06 08:56 UTC, me4502 commented on src/main/java/com/me4502/modularframework/ModuleController.java
> +        for(ModuleWrapper wrapper : moduleSet) {
This can be done with the Java 8 Streams API

2017-01-06 08:56 UTC, me4502 commented on src/main/java/com/me4502/modularframework/module/Module.java
>      String moduleName();
I think it may be worth making this default to ID. I'd prefer to not have it require multiple things like this.

2017-01-06 08:56 UTC, me4502 commented on src/main/java/com/me4502/modularframework/module/ModuleWrapper.java
> +    public Optional<String> getVersion() {
This will only be empty in exceptional circumstances. I'd just have it return null if an exception is thrown rather than using optional.

2017-01-06 08:56 UTC, me4502 commented on src/main/java/com/me4502/modularframework/module/ModuleWrapper.java
> +    public Optional<List<String>> getAuthors() {
Same as above

2017-01-07 05:44 UTC, me4502 commented on src/main/java/com/me4502/modularframework/module/ModuleWrapper.java
> +        return moduleClassName.toLowerCase();
Once default is done, this won't be needed. It'll return null in exceptional circumstances.

2017-01-07 23:51 UTC, me4502 commented on src/main/java/com/me4502/modularframework/module/ModuleWrapper.java
> +            if(getAnnotation().moduleName().equals("")) {
I meant have moduleName's default implementation just hook back to moduleId

2017-01-07 23:51 UTC, me4502 commented on src/main/java/com/me4502/modularframework/module/Module.java
> +    String moduleName() default "";
default moduleId();

2017-01-08 00:19 UTC, me4502 approved these changes

2017-01-08 00:19 UTC, merged