Add Spigot Implementation
me4502/ModularFramework pull request #9
Opened 2017-08-21 05:16 UTC by connorhartley

This is a fairly big change so any feedback and criticism is welcome as I wasn't 100% sure how you would like me to implement this.

2017-08-21 07:39 UTC, me4502 requested changes
Overall pretty good. I still think a core module is the best way to do this. 90% of this is unnecessary code duplication.

2017-08-21 07:39 UTC, me4502 commented on build.gradle
> +    project.ext.versionNumber = '1.8.5'
Please bump this to 1.9 for this PR.

2017-08-21 07:39 UTC, me4502 commented on modularframework-spigot/build.gradle
> +//    id "tech.ferus.gradle.spigotgradle" version "1.0.5"
So this isn't being used? Any specific reasons?

2017-08-21 07:39 UTC, me4502 commented on modularframework-spigot/src/main/java/com/me4502/modularframework/ModularFramework.java
> +public class ModularFramework extends JavaPlugin {
It'd make most sense to make ModularFramework an interface with default static methods in it, that gets implemented in both SpongeModularFramework and BukkitModularFramework. Make sure this is an interface however, as Java doesn't support multiple inheritances.

2017-08-21 07:39 UTC, me4502 commented on modularframework-spigot/src/main/java/com/me4502/modularframework/ModuleController.java
> +public class ModuleController<T extends JavaPlugin> {
The only Bukkit reference here is `extends JavaPlugin`. This should be in a core module.

2017-08-21 07:39 UTC, me4502 commented on modularframework-spigot/src/main/java/com/me4502/modularframework/ShadedModularFramework.java
> +public class ShadedModularFramework {
Same as other. This should be in core, and should automatically detect Spigot/Sponge etc and delegate to the appropriate system.

2017-08-21 07:39 UTC, me4502 commented on modularframework-spigot/src/main/java/com/me4502/modularframework/module/ModuleWrapper.java
> +public class ModuleWrapper<T> {
Make this an interface (Preferable - with default methods) or class with all common code, and then make a Sponge and Bukkit variant with the implementation for any platform specific things.

2017-08-21 07:39 UTC, me4502 commented on modularframework-spigot/src/main/java/com/me4502/modularframework/module/guice/ModuleContainer.java
> +public @interface ModuleContainer {
There's no need to have this a second time if you have a core module :)

2017-08-21 07:39 UTC, me4502 commented on modularframework-spigot/src/main/java/com/me4502/modularframework/module/guice/ModuleInjector.java
> +public class ModuleInjector extends AbstractModule {
Ditto

2017-08-22 06:00 UTC, connorhartley commented on modularframework-spigot/build.gradle
> +//    id "tech.ferus.gradle.spigotgradle" version "1.0.5"
This is because we're not making it a plugin yet until we figure out how we're going to do that for Spigot and Sponge.

2017-08-22 09:01 UTC, me4502 requested changes

2017-08-22 09:01 UTC, me4502 commented on .gitignore
> +com.me4502.modularframework.ModularFramework.iml
*.iml :)

2017-08-22 09:01 UTC, me4502 commented on modularframework-core/src/main/java/com/me4502/modularframework/ModuleController.java
> +public abstract class ModuleController<T> {
Rip class comment :(

2017-08-22 09:01 UTC, me4502 commented on modularframework-core/src/main/java/com/me4502/modularframework/ModuleController.java
> +    public ModuleController(T plugin) {
Rip constructor comment :(

2017-08-22 09:01 UTC, me4502 commented on modularframework-core/src/main/java/com/me4502/modularframework/ModuleController.java
> +    public abstract void registerModule(String className);
Rip method comment :(

2017-08-22 09:01 UTC, me4502 commented on modularframework-spigot/build.gradle
> +//    id "tech.ferus.gradle.spigotgradle" version "1.0.5"
Ahhh true

2017-08-22 19:20 UTC, connorhartley commented on .gitignore
> +com.me4502.modularframework.ModularFramework.iml
Agh I missed that. xD

2017-12-02 00:57 UTC, merged